testedysabdsdasmdklsnkljndld

fdajfds
testedysabdsdasmdklsnkljndld

fdajfds
testedysabdsdasmdklsnkljndld

fdajfdstestedysabdsdasmdklsnkljndld

fdajfdstestedysabdsdasmdklsnkljndld

fdajfdstestedysabdsdasmdklsnkljndld

fdajfdstestedysabdsdasmdklsnkljndld

fdajfdstestedysabdsdasmdklsnkljndld

fdajfdstestedysabdsdasmdklsnkljndld

fdajfdstestedysabdsdasmdklsnkljndld

fdajfds
@yield('content_mobile_render')